datos = {
    'Estado': [
        'Aguascalientes',
        'Baja California',
        'Baja California',
        'Baja California',
        'Baja California',
        'Baja California',
        'Baja California Sur',
        'Baja California Sur',
        'Baja California Sur',
        'Campeche',
        'Chiapas',
        'Chiapas',
        'Chiapas',
        'Chiapas',
        'Chihuahua',
        'Chihuahua',
        'Chihuahua',
        'Coahuila',
        'Coahuila',
        'Colima',
        'Colima',
        'Colima',
        'Cd. de México',
        'Durango',
        'Estado de México',
        'Guanajuato',
        'Guerrero',
        'Guerrero',
        'Hidalgo',
        'Jalisco',
        'Jalisco',
        'Jalisco',
        'México',
        'Michoacán',
        'Michoacán',
        'Michoacán',
        'Morelos',
        'Nayarit',
        'Nayarit',
        'Nuevo León',
        'Oaxaca',
        'Oaxaca',
        'Oaxaca',
        'Puebla',
        'Querétaro',
        'Quintana Roo',
        'Quintana Roo',
        'San Luis Potosí',
        'San Luis Potosí',
        'Sonora',
        'Sinaloa',
        'Sinaloa',
        'Sinaloa',
        'Sonora',
        'Sonora',
        'Sonora',
        'Sonora',
        'Tabasco',
        'Tamaulipas',
        'Tamaulipas',
        'Veracruz',
        'Yucatán',
        'Yucatán'
    ],
    'Ciudad': [
        'Aguascalientes',
        'Isla Cedros',
        'Ensenada',
        'Mexicali',
        'San Felipe',
        'Tijuana',
        'La Paz',
        'Loreto',
        'Los Cabos',
        'Cd. Del Carmen',
        'Comitán',
        'Palenque',
        'Tapachula',
        'Tuxtla Gutiérrez',
        'Cd. Juárez',
        'Chihuahua',
        'Nuevo Casas Grandes',
        'Ciudad Acuña',
        'Saltillo',
        'Colima',
        'Manzanillo',
        'Manzanillo',
        'Cd. De México',
        'Durango',
        'Toluca',
        'León',
        'Acapulco',
        'Ixtapa/Zihuatanejo',
        'Pachuca',
        'Guadalajara',
        'Lagos de Moreno',
        'Puerto Vallarta',
        'Atizapán',
        'Apatzingán',
        'Uruapan',
        'Zamora',
        'Cuernavaca',
        'Tepic',
        'Tepic',
        'Monterrey',
        'Huatulco',
        'Oaxaca',
        'Puerto Escondido',
        'Tehuacán',
        'Querétaro',
        'Chetumal',
        'Isla Mujeres',
        'San Luis Potosí',
        'Tamuín',
        'Cananea',
        'Culiacán',
        'Los Mochis',
        'Mazatlán',
        'Cd. Obregón',
        'Guaymas',
        'Hermosillo',
        'Nogales',
        'Villahermosa',
        'Reynosa',
        'Tampico',
        'Veracruz',
        'Chichén Itzá',
        'Mérida'
    ],
    'Codigo_IATA': [
        'AGU',
        'CDI',
        'ESE',
        'MXL',
        'SFH',
        'TIJ',
        'LAP',
        'LTO',
        'SJD',
        'CME',
        'CJT',
        'PQM',
        'TAP',
        'TGZ',
        'CJS',
        'CUU',
        'NCG',
        'ACN',
        'SLW',
        'CLQ',
        'ZLO',
        'MEX',
        'DGO',
        'TLC',
        'BJX',
        'ACA',
        'ZIH',
        'PCA',
        'GDL',
        'LOM',
        'PVR',
        'JJC',
        'AZG',
        'UPN',
        'ZMM',
        'CVJ',
        'TNY',
        'TPQ',
        'MTY',
        'HUX',
        'IZT',
        'PXM',
        'SCX',
        'QRO',
        'CTM',
        'ISJ',
        'TUY',
        'TSL',
        'CNA',
        'CUL',
        'LMM',
        'MZT',
        'CEN',
        'GYM',
        'HMO',
        'NOG',
        'CPX',
        'REX',
        'TAM',
        'JAL',
        'CZA',
        'MID',
        'TZM'
    ],
    'Pasajeros': [
        258,
        1808,
        2365,
        4236,
        2030,
        3501,
        2628,
        2963,
        3520,
        4054,
        3914,
        3215,
        3316,
        2091,
        3052,
        759,
        3019,
        2219,
        3783,
        4166,
        3148,
        342,
        1137,
        2018,
        3824,
        120,
        3196,
        3749,
        3824,
        3020,
        2832,
        827,
        919,
        4281,
        447,
        2217,
        1428,
        2942,
        1474,
        3329,
        2268,
        3549,
        862,
        2369,
        4029,
        1953,
        584,
        680,
        1801,
        316,
        0,
        0,
        0,
        946,
        3061,
        231,
        3321,
        920,
        4366,
        3336,
        3314,
        2114,
        1961
    ],
    'Vuelos_Sinaloa': [
        1,
        4,
        2,
        3,
        3,
        3,
        4,
        1,
        2,
        3,
        1,
        1,
        4,
        4,
        4,
        2,
        3,
        2,
        1,
        3,
        2,
        3,
        1,
        1,
        4,
        1,
        3,
        2,
        3,
        3,
        1,
        2,
        3,
        4,
        4,
        3,
        2,
        4,
        1,
        4,
        4,
        2,
        3,
        2,
        3,
        4,
        3,
        2,
        1,
        3,
        0,
        0,
        0,
        4,
        3,
        1,
        3,
        4,
        4,
        1,
        2,
        4,
        4
    ]
}